#!/bin/bash

n=9

projects=(
"libft"
"gnl"
"printf"
"b2br"
"minitalk"
"pipex"
"so_long"
"fdf"
"fract-ol"
"push_swap"
)

urls=(
"https://cdn.intra.42.fr/pdf/pdf/70131/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/81792/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/81372/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/81774/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/56849/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/66249/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/83099/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/70122/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/65475/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/70135/en.subject.pdf"
)

for i in $(seq 0 $n)
do
	filename=~/42/cursus/core/.subjects/${projects[$i]}.pdf
	echo "Downloading ${urls[$i]} in $filename ..."
	curl ${urls[$i]} --output $filename
done

echo "Download completato"
git add *.pdf
