#!/bin/bash

n=9

projects=(
"libft"
"gnl"
"printf"
"b2br"
"minitalk"
"pipex"
"so_long"
"fdf"
"fract-ol"
"push_swap"
)

urls=(
"https://cdn.intra.42.fr/pdf/pdf/98026/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101896/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101895/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101894/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101902/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101901/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101907/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101908/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101909/en.subject.pdf"
"https://cdn.intra.42.fr/pdf/pdf/101897/en.subject.pdf"
)

for i in $(seq 0 $n)
do
	filename=~/42/cursus/core/.subjects/${projects[$i]}.pdf
	echo "Downloading ${urls[$i]} in $filename ..."
	curl ${urls[$i]} --output $filename
done

echo "Download completato"
git add *.pdf
